config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "proposals#index"
  resources :proposals do
    resources :comments, only: :create
  end
  
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :proposal
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :proposal
end

app/models/occupation.rb
class Occupation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '法人営業部' },
    { id: 3, name: '法人営業部 第1チーム' },
    { id: 4, name: '法人営業部 第2チーム' },
    { id: 5, name: '法人営業部 第3チーム' },
    { id: 6, name: '法人営業部 第4チーム' }
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'マネージャー' },
    { id: 3, name: 'チーフ' },
    { id: 4, name: 'リーダー' },
    { id: 5, name: 'スタッフ' },
    { id: 6, name: '担当' }
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  has_many :user_proposals
  has_many :users, through: :user_proposals
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :title,       length: { maximum: 20 }
    validates :detail,      length: { maximum: 250 }
    validates :term_start
    validates :term_end
    validates :target_group
    validates :numeric
    validates :budget, numericality: { only_integer: true }
    validates :payment
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: '全角文字を使用してください' }
  # VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  # validates :password, format: { with: VALID_PASSWORD_REGEX }
  validates :phone_number, format: { with: /\A\d{10,11}\z/ }
  validates :occupation_id, :position_id, numericality: { other_than: 1 }

  has_many :user_proposals
  has_many :proposals, through: :user_proposals
  has_many :comments
  has_many :likes

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :occupation
  belongs_to :position

  def liked_by?(proposal_id)
    likes.where(proposal_id: proposal_id).exists?
  end
end

app/models/user_proposal.rb
class UserProposal < ApplicationRecord
  belongs_to :user
  belongs_to :proposal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :occupation_id, :position_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @proposal = Proposal.find(params[:proposal_id])
    @comment = @proposal.comments.new(comment_params)
    @comment.save
    redirect_to "/proposals/#{@comment.proposal.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    Like.create(user_id: current_user.id, proposal_id: params[:id])
    redirect_to proposal_path
  end

  def destroy
    Like.find_by(user_id: current_user.id, proposal_id: params[:id]).destroy
    redirect_to proposal_path
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new]
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show, :new, :create]

  def index
    @proposals = Proposal.all.order('created_at DESC')
  end

  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = Proposal.new(proposal_params)
    # binding.pry
    if @proposal.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @proposal.comments.includes(:user)
    @like = Like.new
    @likes = @proposal.likes.includes(:user)
  end

  def edit
  end

  def update
    if @proposal.update(proposal_params)
      redirect_to proposal_path
    else
      render :edit
    end
  end

  def destroy
    @proposal.destroy
    redirect_to root_path
  end

  private

  def proposal_params
    params.require(:proposal).permit(
      :title,
      :detail,
      :term_start,
      :term_end,
      :target_group,
      :numeric,
      :budget,
      :payment,
      user_ids: []
    )
  end

  def set_proposal
    @proposal = Proposal.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in? && current_user.id == @proposal.user_ids[0]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProposalDocuments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="test/css" >
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cherry+Swash:700" rel="stylesheet">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/proposals/_header_proposal.html.erb
<div class="nav">
  <div class="nav-rogo mt-3">
    <%= link_to "Proposal Documents.", root_path, class: "rogo" %>
  </div>
  <% if user_signed_in? %>
    <ul class="list-right">
      <li class="mt-5 mx-3">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "user-log" %>
      </li>
      <li class="mt-5 mx-3">
        <%= link_to "#{current_user.name}", "#", class: "user-log" %>
      </li>
    </ul>
  <% else %>
    <ul class="list-right">
      <li class="mt-5 mx-3">
        <%= link_to "ログイン", new_user_session_path, class: "user-log" %>
      </li>
      <li class="mt-5 mx-3">
        <%= link_to "新規登録", new_user_registration_path, class: "user-log" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/proposals/_main_edit_proposal.html.erb
<div class="container">
  <div class="row">
    <%= form_with model: @proposal, local: true do |f| %>
      <div class="form">
        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label">タイトル:</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label">内容:</label>
          <%= f.text_area :detail, class: "form-control" %>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">期間（開始）:</label>
            <%= f.date_field :term_start, class: "form-control" %>
          </div>
          <div class="col-md-6 mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">期間（終了）:</label>
            <%= f.date_field :term_end, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">ターゲット:</label>
            <%= f.text_field :target_group, class: "form-control" %>
          </div>
          <div class="col-md-6 mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">目標:</label>
            <%= f.text_field :numeric, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">予算:</label>
            <%= f.number_field :budget, class: "form-control" %>
          </div>
          <div class="col-md-8 mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">支払処理:</label>
            <%= f.text_field :payment, class: "form-control" %>
          </div>
        </div>
        
        <div class="row">
          <input name="proposal[user_ids][]" type="hidden" value=<%= current_user.id %>>
          <% i = 1 %>
          <% 4.times do %>
            <div class="col-md-6 ">
              <div class="mt-3 weight-bold-text">
                決裁者の選択（<%=i%>人目）
              </div>
              <div class="mb-3" >
                <select name="proposal[user_ids][]">
                  <option value=""><%=i%>人目の決裁者を選択してください</option>
                  <% User.where.not(id: current_user.id).each do |user| %>
                    <option value=<%= user.id %>><%= user.name %><%= " (#{user.occupation.name}: #{user.position.name})" %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <% i += 1 %>
          <% end %>
        </div>


        <div>
          <%= f.submit '登録', class: 'mt-4 btn btn-outline-secondary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/proposals/_main_new.html.erb
<div class="container">
  <div class="row">
    <%= form_with model: @proposal, local: true do |f| %>
      <div class="form">
        <div class="mb-4">
          <label for="exampleFormControlTextarea1" class="mt-3 form-label" >タイトル:</label>
          <%= f.text_field :title, class: "form-control", placeholder: "例）超大型巨人の活用方法"%>
        </div>
        <div class="mb-4">
          <label for="exampleFormControlTextarea1" class="form-label">内容:</label>
          <%= f.text_area :detail, class: "form-control", placeholder: "例）巨人化する際の大爆発を利用して敵艦隊を殲滅させる。" %>
        </div>
        <div class="row">
          <div class="col-md-6 mb-4">
            <label for="exampleFormControlTextarea1" class="form-label">期間（開始）:</label>
            <%= f.date_field :term_start, class: "form-control" %>
          </div>
          <div class="col-md-6 mb-4">
            <label for="exampleFormControlTextarea1" class="form-label">期間（終了）:</label>
            <%= f.date_field :term_end, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-4">
            <label for="exampleFormControlTextarea1" class="form-label">ターゲット:</label>
            <%= f.text_field :target_group, class: "form-control", placeholder: "例）アマルの民" %>
          </div>
          <div class="col-md-6 mb-4">
            <label for="exampleFormControlTextarea1" class="form-label">目標:</label>
            <%= f.text_field :numeric, class: "form-control", placeholder: "例）パラディ島の死守" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 mb-4">
            <label for="exampleFormControlTextarea1" class="form-label">予算:</label>
            <%= f.number_field :budget, class: "form-control", placeholder: "例）五円" %>
          </div>
          <div class="col-md-8 mb-4">
            <label for="exampleFormControlTextarea1" class="form-label">支払処理:</label>
            <%= f.text_field :payment, class: "form-control", placeholder: "例）政策経費として処理" %>
          </div>
        </div>

        <div class="row">
          <input name="proposal[user_ids][]" type="hidden" value=<%= current_user.id %>>
          <% i = 1 %>
          <% 4.times do %>
            <div class="col-md-6 ">
              <div class="mt-3 weight-bold-text">
                決裁者の選択（<%=i%>人目）
              </div>
              <div class="mb-3" >
                <select name="proposal[user_ids][]">
                  <option value=""><%=i%>人目の決裁者を選択してください</option>
                  <% User.where.not(id: current_user.id).each do |user| %>
                    <option value=<%= user.id %>><%= user.name %><%= " (#{user.occupation.name}: #{user.position.name})" %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <% i += 1 %>
          <% end %>
        </div>

        <div>
          <%= f.submit '登録', class: 'mt-4 mb-3 btn btn-outline-info' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/proposals/_main_proposal.html.erb
<div class="container">
  <div class="row">
    <div class="mt-5 mx-5 occupation-head">法人営業部 第3チーム</div>
    <div class="card-content">
      <% @proposals.each do |proposal| %>
        <div class="card-name">
          <%= link_to proposal_path(proposal.id), class: "proposal-tag" do %>
            <div class="card mt-5 mx-3" style="width: 20rem;">
              <div class="card-body">
                <p class="card-title">タイトル：<br><%= proposal.title %></p>
              </div>
              <ul class="list-group list-group-flush">
                  <li class="list-group-item list-contet">作成者：　　　<%= proposal.users[0].name %></li>
                <li class="list-group-item list-contet">作成日：　　　<%= proposal.created_at.strftime('%Y年%m月%d日') %></li>
                <% if proposal.likes.count == 4 %>
                  <li class="list-group-item list-contet list-ok">ステータス：　完了済み</li>
                <% else %>
                  <li class="list-group-item list-contet">ステータス：　未</li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/proposals/_main_show_proposal.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      法人営業部 第3チーム
    </div>
    <div class="col-md-6 mt-3">
      作成者：<%= @proposal.users[0].name%> さん
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 show-header2">
      <% if user_signed_in? && current_user.id == @proposal.users[0].id %>
        <%= link_to "編集", edit_proposal_path, class: "mx-2 btn btn-secondary user-btn" %>
        <%= link_to '削除', proposal_path(@proposal.id), method: :delete, class: "mx-2 btn btn-secondary user-btn" %>
      <% end %>
      <% if user_signed_in? && @proposal.users.include?(current_user) && @proposal.users[0].id != current_user.id %>
        <% if current_user.liked_by?(@proposal.id) %>
          <%= link_to "確認取消し", destroy_like_path(@proposal), method: :DELETE, type: "button", class: "mx-2 btn btn-warning user-btn1" %>
        <% else %>
          <%= link_to "確認済み", create_like_path(@proposal), method: :POST, type: "button", class: "mx-2 btn btn-warning user-btn1" %>
        <% end %>
      <% end %>
      <%= link_to "戻る", root_path, type: "button", class: "mx-2 btn btn-outline-info user-btn" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 mt-3 show-header1">＜決裁者＞
      <table class="table table-bordered">
        <tbody>

          <tr>
            <% i = 1 %>
            <% 4.times do %>
              <td class="col-3 check-box">
                <% if @proposal.users[i] %>
                  <%= @proposal.users[i].position.name %>
                <% end %>
              </td>
              <% i += 1 %>
            <% end %>
          </tr>

          <tr>
            <% i = 1 %>
            <% 4.times do %>
              <td class="col-3 check-box">
                <% if @proposal.users[i] %>
                  <%= @proposal.users[i].name %>
                <% end %>
              </td>
              <% i += 1 %>
            <% end %>
          </tr>

          <tr>
            <% i = 1 %>
            <% 4.times do %>
              <% if @proposal.users[i].liked_by?(@proposal.id) %>
                <td class="col-3 check-box">完了</td>
              <% else %>
                <td class="col-3 check-box1">未</td>
              <% end %>
              <% i += 1 %>
            <% end %>
          </tr>

        </tbody>
      </table>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-12">＜提案書詳細＞
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td class="detail-title">タイトル：</td>
            <td class="detail-value"><%= @proposal.title %></td>
          </tr>
          <tr>
            <td class="detail-title">内容：</td>
            <td class="detail-value"><%= @proposal.detail %></td>
          </tr>
          <tr>
            <td class="detail-title">期間：</td>
            <td class="detail-value"><%= @proposal.term_start.strftime('%Y年%m月%d日') %>  -  <%= @proposal.term_end.strftime('%Y年%m月%d日') %></td>
          </tr>
          <tr>
            <td class="detail-title">対象者：</td>
            <td class="detail-value"><%= @proposal.target_group %></td>
          </tr>
          <tr>
            <td class="detail-title">目標：</td>
            <td class="detail-value"><%= @proposal.numeric %></td>
          </tr>
          <tr>
            <td class="detail-title">予算：</td>
            <td class="detail-value"><%= @proposal.budget.to_s(:delimited) %>円（税抜）</td>
          </tr>
          <tr>
            <td class="detail-title">費用処理：</td>
            <td class="detail-value"><%= @proposal.payment %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row mt-4 mx-1">＜コメント＞
    <div class="col-md-12 show-comments">
      <% if user_signed_in? && @proposal.users.include?(current_user) %>
        <%= form_with(model: [@proposal, @comment], local: true) do |form| %>
          <%= form.text_area :comment, class: "mt-3 form-control", placeholder: "コメントする", rows: "2" %>
          <%= form.submit "プッシュ", class: "mt-3 mx-2 btn btn-outline-secondary" %>
        <% end %>
        <div class="mt-3 comments_list">
        <div class="comment-title">< コメント一覧 ></div>
        <% @comments.reverse_each do |comment| %>
          <div>
            <div class="mt-2 comment-comment">
              <%= comment.comment %>
            </div>
            <div class="comment-info">
              (<%= comment.user.name %>:<%= comment.created_at.strftime('%Y年%m月%d日') %>)
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="my-3 mx-3">
          <p>※※※ コメントの閲覧/投稿は決裁メンバーのみ可能です ※※※</p>
        </div>
      <% end %>
    </div>  
  </div>
</div>

app/views/proposals/_side_proposal.html.erb
<div class="side">
  <% Occupation.where.not(id: [1,2]).each do |occupation| %>
    <div class="occupation">
      <div class="occupation-name">
        <a href="#"><%= occupation.name %></a>
      </div>
    </div>
  <% end %>
  <div class="proposal-btn">
    <a href="/proposals/new" class="btn btn-outline-info">
      New 提案書
    </a>
  </div>
  <div class="footer">
    <div class="footer-2">Proposal Documents</div>
    <div class="footer-1">End&Start.co</div>
    <div class="footer-1">address:kobe city888</div>
    <div class="footer-1">tel:080-xxx-xxx</div>
    <div class="footer-1">&copy; 2021</div>
  </div>
</div>

app/views/proposals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 header">
      <%= render "header_proposal" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3 side-bar">
      <%= render "side_proposal" %>
    </div>
    <div class="col-sm-9 main">
      <%= render "main_edit_proposal" %>
    </div>
  </div>
</div>

app/views/proposals/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 header">
      <%= render "header_proposal" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3 side-bar">
      <%= render "side_proposal" %>
    </div>
    <div class="col-sm-9 main">
      <%= render "main_proposal" %>
    </div>
  </div>
</div>

app/views/proposals/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 header">
      <%= render "header_proposal" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3 side-bar">
      <%= render "side_proposal" %>
    </div>
    <div class="col-sm-9 main">
      <%= render "main_new" %>
    </div>
  </div>
</div>

app/views/proposals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 header">
      <%= render "header_proposal" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3 side-bar">
      <%= render "side_proposal" %>
    </div>
    <div class="col-sm-9 main">
      <%= render "main_show_proposal" %>
    </div>
  </div>
</div>